<a href="https://colab.research.google.com/github/shrtritika488-hash/maths/blob/main/workshop1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#1 Empty array 2x2
a = np.empty((2,2))
print(a)

#2. All ones array 4x2
b = np.ones((4,2))
print(b)

#3. Array with fill value
c = np.full((3,3), 7)
print(c)

#4. Zeros like existing array
arr = np.array([[1,2,3],[4,5,6]])
d = np.zeros_like(arr)
print(d)

#5. Ones like existing array
e = np.ones_like(arr)
print(e)

#6. Convert list to numpy array
new_list = [1,2,3,4]
f = np.array(new_list)
print(f)


[[4.98378022e-315 0.00000000e+000]
 [4.94065646e-324 6.85163898e-310]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[1 2 3 4]


In [ ]:
import numpy as np

#1.Array from 10 to 49
a = np.arange(10, 50)
print(a)

#2. 3x3 matrix from 0 to 8
b = np.arange(9).reshape(3,3)
print(b)

#3. Identity matrix 3x3
c = np.eye(3)
print(c)

#4. Random array of size 30 + mean
d = np.random.random(30)
print("Mean:", d.mean())

#5. 10x10 random array → min & max
e = np.random.random((10,10))
print("Min:", e.min(), "Max:", e.max())

#6. Zero array size 10 → replace 5th with 1
f = np.zeros(10)
f[4] = 1     # index starts at 0
print(f)

#7. Reverse array
arr = np.array([1,2,0,0,4,0])
g = arr[::-1]
print(g)

#8. 2D array with 1 on border, 0 inside
h = np.ones((5,5))
h[1:-1, 1:-1] = 0
print(h)

#9. 8x8 checkerboard pattern
i = np.zeros((8,8))
i[1::2, ::2] = 1
i[::2, 1::2] = 1
print(i)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean: 0.5246509450889285
Min: 0.015425815794879227 Max: 0.99643019478316
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#1 Addition
print(x + y)

#2 Subtraction
print(x - y)

#3 Multiply with integer
print(x * 3)

#4 Square of each element
print(x**2)

#5 Dot products
print("v·w =", np.dot(v,w))
print("x·v =", np.dot(x,v))
print("x·y =", np.dot(x,y))

#6 Concatenate x & y (row) and v & w (column)
print(np.concatenate((x,y), axis=0))
print(np.vstack((v,w)).T)

#7 Concatenate x & v → explanation
try:
    print(np.concatenate((x,v)))
except Exception as e:
    print("Error:", e)
    print("Reason: x is 2D but v is 1D → shapes do not match!")


[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
v·w = 219
x·v = [29 77]
x·y = [[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x is 2D but v is 1D → shapes do not match!


In [ ]:
import numpy as np

#------------------------------
# Problem 4 – Matrix Operations
#------------------------------
A = np.array([[3,4],
              [7,8]])

B = np.array([[5,3],
              [2,1]])

#1 Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
print("A * A^-1 =\n", A @ A_inv)

#2 Prove AB != BA
AB = A @ B
BA = B @ A
print("\nA * B =\n", AB)
print("\nB * A =\n", BA)

#3 Prove (AB)^T = B^T * A^T
print("\n(AB)^T =\n", AB.T)
print("\nB^T * A^T =\n", B.T @ A.T)

#------------------------------
# Solve Linear Equations
#------------------------------
# System:
# 2x – 3y +  z = –1
# x –  y + 2z = –3
# 3x +  y –  z = 9
A = np.array([[ 2, -3, 1],
              [ 1, -1, 2],
              [ 3,  1, -1]])

B = np.array([-1, -3, 9])

# Solve using linalg.solve
solution = np.linalg.solve(A, B)
print("\nSolution using solve() =\n", solution)

# Solve using inverse
A_inv = np.linalg.inv(A)
solution2 = A_inv @ B
print("\nSolution using inverse =\n", solution2)

A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

A * B =
 [[23 13]
 [51 29]]

B * A =
 [[36 44]
 [13 16]]

(AB)^T =
 [[23 51]
 [13 29]]

B^T * A^T =
 [[23 51]
 [13 29]]

Solution using solve() =
 [ 2.  1. -2.]

Solution using inverse =
 [ 2.  1. -2.]


In [14]:
import numpy as np
import time

# -------------------------
# 1. Element-wise Addition
#-------------------------
# Python list
L1 = list(range(1_000_000))
L2 = list(range(1_000_000))
start = time.time()
L3 = [L1[i] + L2[i] for i in range(1_000_000)]
print("List addition time:", time.time() - start)

# NumPy
A1 = np.arange(1_000_000)
A2 = np.arange(1_000_000)
start = time.time()
A3 = A1 + A2
print("NumPy addition time:", time.time() - start)

#-------------------------
#2. Multiplicatio0n
#-------------------------
# List
start = time.time()
L4 = [L1[i] * L2[i] for i in range(1_000_000)]
print("List multiply time:", time.time() - start)

# NumPy
start = time.time()
A4 = A1 * A2
print("NumPy multiply time:", time.time() - start)

#-------------------------
#3 .Dot Product
#-------------------------

# List
start = time.time()
dot_list = sum(L1[i] * L2[i] for i in range(1_000_000))
print("List dot time:", time.time() - start)

#cNumPy
start = time.time()
dotnp = np.dot(A1, A2)
print("NumPy dot time:", time.time() - start)

#-------------------------
#4. Matrix Multiplication (1000x1000)
#-------------------------

# Python list
import random
M1 = [[random.random() for _ in range(1000)] for _ in range(1000)]
M2 = [[random.random() for _ in range(1000)] for _ in range(1000)]

start = time.time()
result = [[sum(a*b for a,b in zip(row,col)) for col in zip(*M2)] for row in M1]
print("List matrix multiply:", time.time() - start)

# NumPy
A = np.random.random((1000,1000))
B = np.random.random((1000,1000))

start = time.time()
C = A @ B
print("NumPy matrix multiply:", time.time() - start)

List addition time: 0.11678361892700195
NumPy addition time: 0.0022933483123779297
List multiply time: 0.1171262264251709
NumPy multiply time: 0.002369403839111328
List dot time: 0.1107633113861084
NumPy dot time: 0.0022134780883789062
List matrix multiply: 184.16741108894348
NumPy matrix multiply: 0.06073474884033203
